spring.application.name=file-processor-service
server.port=8080

# AWS S3 LocalStack Configuration
aws.s3.endpoint=http://localstack.cloud-native-app:4566
aws.s3.region=us-east-1
aws.s3.bucket=processor-bucket

# Actuator & Monitoring
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
